"""initial_schema

Revision ID: d05a36f38db1
Revises: 
Create Date: 2025-12-06 02:25:02.955128

"""
from collections.abc import Sequence

import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

from alembic import op

# revision identifiers, used by Alembic.
revision: str = 'd05a36f38db1'
down_revision: str | Sequence[str] | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('hashed_password', sa.String(length=255), nullable=False),
    sa.Column('full_name', sa.String(length=255), nullable=False),
    sa.Column('tier', postgresql.ENUM('FREE', 'PREMIUM', name='user_tier'), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_index('ix_users_email_lower', 'users', ['email'], unique=False)
    op.create_index('ix_users_tier', 'users', ['tier'], unique=False)
    op.create_table('cvs',
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('filename', sa.String(length=255), nullable=False),
    sa.Column('file_path', sa.String(length=512), nullable=False),
    sa.Column('raw_text', sa.Text(), nullable=True),
    sa.Column('parsed_data', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('is_primary', sa.Boolean(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_cvs_user_id'), 'cvs', ['user_id'], unique=False)
    op.create_index('ix_cvs_user_primary', 'cvs', ['user_id', 'is_primary'], unique=False)
    op.create_table('tailored_cvs',
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('base_cv_id', sa.UUID(), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['base_cv_id'], ['cvs.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_tailored_cvs_base_cv', 'tailored_cvs', ['base_cv_id'], unique=False)
    op.create_index(op.f('ix_tailored_cvs_base_cv_id'), 'tailored_cvs', ['base_cv_id'], unique=False)
    op.create_index('ix_tailored_cvs_user_base', 'tailored_cvs', ['user_id', 'base_cv_id'], unique=False)
    op.create_index(op.f('ix_tailored_cvs_user_id'), 'tailored_cvs', ['user_id'], unique=False)
    op.create_table('saved_jobs',
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('job_source', sa.String(length=50), nullable=False),
    sa.Column('job_external_id', sa.String(length=255), nullable=False),
    sa.Column('job_data', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('status', postgresql.ENUM('SAVED', 'APPLYING', 'APPLIED', 'INTERVIEW', 'OFFER', 'REJECTED', name='job_status'), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('tailored_cv_id', sa.UUID(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['tailored_cv_id'], ['tailored_cvs.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_saved_jobs_source_external', 'saved_jobs', ['job_source', 'job_external_id'], unique=False)
    op.create_index(op.f('ix_saved_jobs_user_id'), 'saved_jobs', ['user_id'], unique=False)
    op.create_index('ix_saved_jobs_user_status', 'saved_jobs', ['user_id', 'status'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_saved_jobs_user_status', table_name='saved_jobs')
    op.drop_index(op.f('ix_saved_jobs_user_id'), table_name='saved_jobs')
    op.drop_index('ix_saved_jobs_source_external', table_name='saved_jobs')
    op.drop_table('saved_jobs')
    op.drop_index(op.f('ix_tailored_cvs_user_id'), table_name='tailored_cvs')
    op.drop_index('ix_tailored_cvs_user_base', table_name='tailored_cvs')
    op.drop_index(op.f('ix_tailored_cvs_base_cv_id'), table_name='tailored_cvs')
    op.drop_index('ix_tailored_cvs_base_cv', table_name='tailored_cvs')
    op.drop_table('tailored_cvs')
    op.drop_index('ix_cvs_user_primary', table_name='cvs')
    op.drop_index(op.f('ix_cvs_user_id'), table_name='cvs')
    op.drop_table('cvs')
    op.drop_index('ix_users_tier', table_name='users')
    op.drop_index('ix_users_email_lower', table_name='users')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    # ### end Alembic commands ###
